AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Max: 120
